{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "DeleteCustomerEntityFailureMessage"
	},
	"Message": "Delete Customer Failed - #ActionResults:Customers_DeleteEntity/error",
	"Title": "Delete Customer",
	"OKCaption": "OK"
}