{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "UpdateCustomerEntityFailMessage"
	},
	"Message": "Failed to Save Customer updates - {#ActionResults:Customer_UpdateEntity/error}",
	"Title": "Update Customer",
	"OKCaption": "OK"
}